Buttons in panel must have "panel-button" class
Otherwise, long stack trace vomit in logs when you lock the screen (no
harmful effects otherwise).  I *suspect* it's because it finds a St.Bin
there, who's only child is a texture (which somehow doesn't have the
has_style_class_name method).

Pasting the garbage here, maybe it helps poor souls who google for it.

JS ERROR: Exception in callback for signal: updated: TypeError: children[index].has_style_class_name is not a function
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:542:15
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:544:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:544:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:544:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:544:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:544:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
setStyleParent@resource:///org/gnome/shell/ui/panel.js:563:22
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_updatePanel@resource:///org/gnome/shell/ui/panel.js:1063:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
_sync@resource:///org/gnome/shell/ui/sessionMode.js:204:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:166:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
activate@resource:///org/gnome/shell/ui/screenShield.js:1279:17
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
lock@resource:///org/gnome/shell/ui/screenShield.js:1328:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:462:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:295:9
_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16